// <auto-generated />
using System;
using ConstructionBudgeting.Sales.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConstructionBudgeting.Sales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260925140022_InitialSales")]
    partial class InitialSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConstructionBudgeting.Sales.Domain.Quotations.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("numeric");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Quotes", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_Quotes_Currency", "\"Currency\" = 'EUR'");

                            t.HasCheckConstraint("CK_Quotes_Total", "\"TotalSalesAmount\" >= 0 AND \"TotalSalesAmount\" = round(\"TotalSalesAmount\", 2)");

                            t.HasCheckConstraint("CK_Quotes_Version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("ConstructionBudgeting.Sales.Domain.Quotations.QuoteLine", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalesUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuoteId", "Id");

                    b.HasIndex("QuoteId", "Position")
                        .IsUnique();

                    b.ToTable("QuoteLines", "sales", t =>
                        {
                            t.HasCheckConstraint("CK_QuoteLines_Amount", "\"LineAmount\" >= 0 AND \"LineAmount\" = round(\"LineAmount\", 2)");

                            t.HasCheckConstraint("CK_QuoteLines_Position", "\"Position\" >= 0");

                            t.HasCheckConstraint("CK_QuoteLines_Price", "\"SalesUnitPrice\" >= 0");

                            t.HasCheckConstraint("CK_QuoteLines_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("ConstructionBudgeting.Sales.Domain.Quotations.QuoteLine", b =>
                {
                    b.HasOne("ConstructionBudgeting.Sales.Domain.Quotations.Quote", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConstructionBudgeting.Sales.Domain.Quotations.Quote", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
